name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
      
      - name: Create .env file if needed
        run: |
          if [ -f ".env.production" ]; then
            cp .env.production .env
          fi
      
      - name: Install SSH client
        run: |
            sudo apt-get update
            sudo apt-get install -y openssh-client
            # Verify installation
            ssh -V

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Generate known_hosts file
          ssh-keyscan -p 22974 -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Deploy to server via SSH
        id: deploy
        run: |
          # Create a temporary directory for deployment
          mkdir -p deploy_package
          
          # Copy required files to the deployment directory
          # This avoids the "file changed as we read it" error
          cp -r $(ls -A | grep -v ".git\|.github\|README.md\|.gitignore\|deploy_package") deploy_package/
          
          # Create the tar archive from the stable deployment directory
          tar -czf deploy.tar.gz -C deploy_package .
          
          # Upload and extract the tar file on remote server using SSH
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]
          do
            echo "SSH deployment attempt $attempt of $max_attempts"
            # Create shared directory structure first
            if ssh -p 22974 -o ConnectTimeout=30 illuminit@tnr1.hodi.host "mkdir -p /home/illuminit/shared_config /home/illuminit/the-end-page" && \
               # Copy .env file to shared directory if it doesn't exist
               scp -P 22974 -o ConnectTimeout=30 deploy.tar.gz illuminit@tnr1.hodi.host:/home/illuminit/temp_deploy.tar.gz && \
               ssh -p 22974 -o ConnectTimeout=30 illuminit@tnr1.hodi.host "
                 # Backup existing .env if it exists in the shared directory
                 if [ -f '/home/illuminit/the-end-page/.env' ] && [ ! -f '/home/illuminit/shared_config/.env' ]; then
                   cp /home/illuminit/the-end-page/.env /home/illuminit/shared_config/.env
                 fi
                 
                 # Extract files but preserve shared config
                 tar -xzf /home/illuminit/temp_deploy.tar.gz -C /home/illuminit/the-end-page && \
                 
                 # Link the shared .env file into the application directory
                 if [ -f '/home/illuminit/shared_config/.env' ]; then
                   ln -sf /home/illuminit/shared_config/.env /home/illuminit/the-end-page/.env
                 fi
                 
                 # Clean up
                 rm /home/illuminit/temp_deploy.tar.gz

                 # Create a symlink to node_modules
                 if [ ! -d '/home/illuminit/the-end-page/node_modules' ]; then
                   ln -s /home/illuminit/nodevenv/the-end-page/20/lib/node_modules /home/illuminit/the-end-page/node_modules
                 fi  
                 
                 # Restart the Node.js application
                 echo 'Restarting Node.js application...'
                 cd /home/illuminit/the-end-page/tmp && touch restart.txt
               "; then
              echo "SSH deployment completed successfully!"
              break
            else
              echo "SSH deployment attempt $attempt failed with exit code $?"
              if [ $attempt -lt $max_attempts ]; then
                echo "Waiting 10 seconds before retrying..."
                sleep 10
              fi
            fi
            attempt=$((attempt+1))
          done
          
          if [ $attempt -gt $max_attempts ]; then
            echo "All SSH deployment attempts failed"
            exit 1
          fi

      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo "✅ Deployment completed successfully!"
          else
            echo "❌ Deployment failed. Check logs for details."
            exit 1
          fi
          
      - name: Send deployment notification
        if: always()
        run: |
          echo "SSH Deployment to server ${{ steps.deploy.outcome == 'success' && 'succeeded! 🚀' || 'failed! ❌' }}"
          echo "Site URL: https://${{ secrets.SSH_HOST }}"
