name: Deploy to cPanel

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
      
      - name: Create .env file if needed
        run: |
          if [ -f ".env.production" ]; then
            cp .env.production .env
          fi
      
      - name: Install SSH client and rsync
        run: |
            sudo apt-get update
            sudo apt-get install -y openssh-client rsync
            # Verify installation
            rsync --version
            ssh -V

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Generate known_hosts file
          ssh-keyscan -p 22974 -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Verify SSH connection
        run: |
          # Test SSH connection before attempting rsync
          ssh -p 22974 -o BatchMode=yes -o ConnectTimeout=5 illuminit@tnr1.hodi.host echo "SSH connection successful"

      - name: Deploy to server via SSH
        id: deploy
        run: |
          # Adding retries to handle potential connection issues
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]
          do
            echo "Deployment attempt $attempt of $max_attempts"
            if rsync -avz -e "ssh -p 22974" --stats --timeout=60 --delete \
              --exclude '.git/' --exclude '.github/' --exclude 'README.md' \
              --exclude '.gitignore' --exclude 'node_modules/' \
              ./ illuminit@tnr1.hodi.host:/home/illuminit/the-end-page/; then
              echo "Rsync completed successfully!"
              break
            else
              echo "Rsync attempt $attempt failed with exit code $?"
              if [ $attempt -lt $max_attempts ]; then
                echo "Waiting 10 seconds before retrying..."
                sleep 10
              fi
            fi
            attempt=$((attempt+1))
          done
          
          if [ $attempt -gt $max_attempts ]; then
            echo "All rsync attempts failed"
            exit 1
          fi
          
      - name: Deployment Status
        if: always()
        run: |
          if [ "${{ steps.deploy.outcome }}" == "success" ]; then
            echo "✅ Deployment completed successfully!"
          else
            echo "❌ Deployment failed. Check logs for details."
            exit 1
          fi
          
      - name: Send deployment notification
        if: always()
        run: |
          echo "SSH Deployment to server ${{ steps.deploy.outcome == 'success' && 'succeeded! 🚀' || 'failed! ❌' }}"
          echo "Site URL: https://${{ secrets.SSH_HOST }}"
